# Generated by Django 2.0.4 on 2018-05-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_num',
        ),
        migrations.AddField(
            model_name='author',
            name='best_books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='代表作', to='books.Book'),
        ),
    ]
