# Generated by Django 2.0.4 on 2018-05-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180521_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '人物', 'verbose_name_plural': '人物'},
        ),
        migrations.AddField(
            model_name='book',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='book',
            name='thoughts',
            field=models.TextField(blank=True, max_length=3000, verbose_name='读后感'),
        ),
        migrations.AlterField(
            model_name='author',
            name='best_books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='代表作', to='books.Book', verbose_name='代表作'),
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='书籍'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ref_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author', verbose_name='相关作者'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ref_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='相关书籍'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, max_length=1, verbose_name='性别'),
        ),
    ]
